name: PDFair
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - ipykernel=6.29.5
  - pypdf=3.17.2
  - pandas=2.2.1
  - beautifulsoup4=4.12.3
  - pip
  - pip:
    - torch==2.1.1
    - torchvision==0.16.1
    - reportlab==4.0.8
    - deepdoctection==0.28
    - filelock==3.13.1
    - huggingface-hub==0.19.4
    
# --- MANUAL INSTALL ---
# $ conda activate PDFair

# $ pip install rlextra==4.0.8 -i https://www.reportlab.com/pypi

# $ sudo apt install tesseract-ocr
# $ sudo apt install libtesseract-dev
# $ sudo apt install tesseract-ocr-nld

# $ sudo apt-get install poppler-utils

# --- CONDA COMMANDS ---
# $ conda env create --name PDFair --file=environment.yml
# $ conda env update --name PDFair --file environment.yml 


